version: '2'

services:
    php:
        build: php7-fpm
        volumes:
            - ../.:/var/www
    nginx:
        build: nginx
        ports:
            - 8080:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
